version: "3.9"

services:
  postgres:
    image: postgres:15.2-bullseye
    container_name: korotkova-postgres
    hostname: postgres
    networks:
      korotkova-network:
        aliases:
          - database
    ports:
      - "5432:5432"
    volumes:
      - /opt/korotkova/pgdata:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: korotkova-redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    image: python:3.11.8-bullseye
    container_name: korotkova-bot
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./:/app
    networks:
      - korotkova-network
    working_dir: /app
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
      - DJANGO_SETTINGS_MODULE=root.settings
      - PYTHONUNBUFFERED=1
    entrypoint: ./entrypoint.sh

networks:
  korotkova-network:
    driver: bridge
