# Generated by Django 5.1.5 on 2025-02-22 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0002_product_category_alter_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="discounted_price",
            field=models.DecimalField(
                db_comment="Item price with discount",
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Item price with discount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="products.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="type",
            field=models.CharField(
                choices=[
                    ("PREPAYMENT", "Prepayment"),
                    ("PARTIAL_PAYMENT", "Partial payment"),
                    ("FULL_PAYMENT", "Full payment"),
                    ("REFUND", "Refund"),
                ],
                db_comment="Payment type",
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
