# Generated by Django 5.1.5 on 2025-03-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_orderitem_discounted_price_alter_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("NOT_PAID", "Not paid"),
                    ("PARTIALLY_PAID", "Partially paid"),
                    ("PAID", "Paid"),
                ],
                db_comment="Payment status",
                default="NOT_PAID",
                max_length=50,
                verbose_name="Payment status",
            ),
        ),
    ]
