# Generated by Django 5.0.1 on 2025-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_user_telegram_id_user_birth_date_usersocial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_comment="Site title",
                        help_text="Title using to show on top of site and browser tab",
                        max_length=255,
                        null=True,
                        verbose_name="Site title",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="Site description",
                        help_text="Description for search robots",
                        null=True,
                        verbose_name="Site description",
                    ),
                ),
                (
                    "tm_label",
                    models.CharField(
                        blank=True,
                        db_comment="Trade mark label",
                        help_text="Using on TM-label as main text",
                        null=True,
                        verbose_name="Trade mark label",
                    ),
                ),
                (
                    "use_yandex_metrika",
                    models.BooleanField(
                        db_comment="Code of Yandex metrika widget",
                        default=False,
                        help_text="Ability to toggle using Yandex metrika widget",
                        verbose_name="Use Yandex metrika widget",
                    ),
                ),
                (
                    "yandex_metrika_code",
                    models.CharField(
                        blank=True,
                        db_comment="Code of Yandex metrika widget",
                        null=True,
                        verbose_name="Code of Yandex metrika widget",
                    ),
                ),
                (
                    "telegram_channel",
                    models.CharField(
                        blank=True,
                        db_comment="Telegram channel name",
                        max_length=100,
                        null=True,
                        verbose_name="Telegram channel name",
                    ),
                ),
                (
                    "telegram_channel_description",
                    models.CharField(
                        blank=True,
                        db_comment="Telegram channel description",
                        null=True,
                        verbose_name="Telegram channel description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
                "db_table": "jw_settings",
                "db_table_comment": "Site dynamic settings",
            },
        ),
    ]
