# Generated by Django 5.0.1 on 2025-01-26 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="personal_discount",
            field=models.DecimalField(
                blank=True,
                db_comment="Percent of personal discount",
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Percent of personal discount",
            ),
        ),
    ]
