# Generated by Django 5.0.1 on 2024-01-29 19:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("app_clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="Creation date and time", verbose_name="Creation date and time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="Update date and time", verbose_name="Update date and time"
                    ),
                ),
                (
                    "total_sum",
                    models.DecimalField(
                        db_comment="Total order sum",
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total order sum",
                    ),
                ),
                (
                    "discount_sum",
                    models.DecimalField(
                        db_comment="Sum of discount",
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sum of discount",
                    ),
                ),
                (
                    "discounted_sum",
                    models.DecimalField(
                        db_comment="Sum with discount",
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Discounted sum",
                    ),
                ),
                (
                    "tax_percent",
                    models.IntegerField(
                        db_comment="Tax percent",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Tax percent",
                    ),
                ),
                (
                    "tax_sum",
                    models.DecimalField(
                        db_comment="Tax sum",
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tax sum",
                    ),
                ),
                (
                    "client_guid",
                    models.ForeignKey(
                        db_column="client_guid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_client",
                        to="app_clients.client",
                        verbose_name="Client GUID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порядок",
                "verbose_name_plural": "Orders",
                "db_table": "jw_order",
            },
        ),
    ]
