# Generated by Django 5.0.1 on 2024-09-13 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "mailing_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Mailing name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BIRTHDAY", "Birthday")],
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "by_email",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification by e-mail",
                        verbose_name="By e-mail",
                    ),
                ),
                (
                    "by_telegram",
                    models.BooleanField(
                        default=False,
                        help_text="Send notification by Telegram",
                        verbose_name="By Telegram",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="notifications_daily",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily notification",
                "verbose_name_plural": "Daily notifications",
                "db_table": "jw_notifications_daily",
                "unique_together": {("type", "is_active")},
            },
        ),
    ]
