# Generated by Django 5.0.1 on 2024-09-16 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdaily",
            name="message_template",
            field=models.TextField(blank=True, null=True, verbose_name="Message template"),
        ),
        migrations.CreateModel(
            name="NotificationMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("TELEGRAM", "Telegram")],
                        max_length=255,
                        verbose_name="Notification type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("NEW", "New"), ("SENT", "Sent"), ("ERROR", "Error")],
                        max_length=255,
                        verbose_name="Status",
                    ),
                ),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_comment="Date and time message sent",
                        verbose_name="Date and time message sent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification mailing",
                "verbose_name_plural": "Notifications mailing",
                "db_table": "jw_notification_mailing",
            },
        ),
    ]
