# Generated by Django 5.0.1 on 2024-03-29 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Bot unique name",
                        max_length=100,
                        unique=True,
                        verbose_name="Unique name",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        db_comment="Bot`s version",
                        max_length=20,
                        verbose_name="Version",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_comment="Bot`s description",
                        max_length=1000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "welcome_message",
                    models.CharField(
                        db_comment="Welcome message",
                        max_length=1000,
                        verbose_name="Welcome message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot",
                "verbose_name_plural": "Bots",
                "db_table": "bot_info",
            },
        ),
        migrations.CreateModel(
            name="Buttons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "text",
                    models.CharField(db_comment="Button`s text", verbose_name="Text"),
                ),
                (
                    "simple_response",
                    models.CharField(
                        blank=True,
                        db_comment="Simple click response",
                        null=True,
                        verbose_name="Simple click response",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        db_comment="Sort order index",
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sort order",
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buttons",
                        to="bot.bot",
                        verbose_name="Bot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Button",
                "verbose_name_plural": "Buttons",
                "db_table": "bot_buttons",
                "unique_together": {("bot", "sort_order")},
            },
        ),
    ]
