# Generated by Django 5.0.1 on 2024-03-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buttons",
            name="text",
            field=models.CharField(db_comment="Button`s text", db_index=True, verbose_name="Text"),
        ),
    ]
