# Generated by Django 5.0.1 on 2024-09-29 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_alter_buttons_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_comment="User ID",
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="User ID",
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        db_comment="Chat ID",
                        max_length=100,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="Chat ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User chat",
                "verbose_name_plural": "User chats",
                "db_table": "bot_user_chat",
                "db_table_comment": "Pairs or user - chat id",
                "unique_together": {("user_id", "chat_id")},
            },
        ),
    ]
