# Generated by Django 5.0.1 on 2024-12-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_userchat"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userchat",
            options={
                "verbose_name": "User chat info",
                "verbose_name_plural": "User chats infos",
            },
        ),
        migrations.AlterModelTableComment(
            name="userchat",
            table_comment="User's chat info",
        ),
        migrations.AlterUniqueTogether(
            name="userchat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userchat",
            name="username",
            field=models.CharField(
                blank=True,
                db_comment="User's name",
                max_length=255,
                null=True,
                verbose_name="Username",
            ),
        ),
    ]
