# Generated by Django 5.0.1 on 2025-01-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_userchat_options_alter_userchat_table_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(db_comment="Chat ID", unique=True, verbose_name="Chat ID"),
                ),
                (
                    "title",
                    models.CharField(db_comment="Channel title", max_length=255, verbose_name="Title"),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        db_comment="Channel link",
                        max_length=255,
                        null=True,
                        verbose_name="Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel",
                "verbose_name_plural": "Channels",
                "db_table": "bot_channel",
            },
        ),
    ]
