# Generated by Django 5.0.1 on 2025-01-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="link",
            field=models.CharField(
                blank=True,
                db_comment="Channel link",
                max_length=255,
                null=True,
                verbose_name="Link",
            ),
        ),
    ]
