# Generated by Django 5.0.1 on 2025-01-11 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Client"),
        migrations.DeleteModel(name="Social"),
    ]
