// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProductsInStockData, GetProductsInStockResponses, GetPublicData, GetPublicResponses, RetrieveData, RetrieveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getPublic = <ThrowOnError extends boolean = false>(options?: Options<GetPublicData, ThrowOnError>) => (options?.client ?? client).get<GetPublicResponses, unknown, ThrowOnError>({ url: '/api/v1/reviews/public/', ...options });

export const getProductsInStock = <ThrowOnError extends boolean = false>(options?: Options<GetProductsInStockData, ThrowOnError>) => (options?.client ?? client).get<GetProductsInStockResponses, unknown, ThrowOnError>({ url: '/api/v1/products/in_stock/', ...options });

export const retrieve = <ThrowOnError extends boolean = false>(options?: Options<RetrieveData, ThrowOnError>) => (options?.client ?? client).get<RetrieveResponses, unknown, ThrowOnError>({ url: '/api/v1/health/', ...options });
