// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://src` | (string & {});
};

/**
 * ReviewDTO
 */
export type ReviewDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Screenshot Url
     *
     * Public URL of the screenshot
     */
    screenshot_url: string;
    /**
     * Client Label
     *
     * Optional caption
     */
    client_label?: string | null;
    /**
     * Quote
     *
     * Optional quote
     */
    quote?: string | null;
    /**
     * Rating
     *
     * Optional 1–5
     */
    rating?: number | null;
    /**
     * Sort Order
     */
    sort_order?: number;
};

/**
 * ProductDTO
 */
export type ProductDto = {
    /**
     * Guid
     */
    guid: string;
    type: ProductTypeDto;
    /**
     * Type Id
     */
    type_id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Price
     */
    price: number | string;
    /**
     * In Stock
     */
    in_stock: boolean;
    /**
     * Files
     */
    files?: Array<ProductFileDto>;
};

/**
 * ImageMeta
 */
export type ImageMeta = {
    size_code?: ImageSizesChoices;
    /**
     * Size
     *
     * Images size (WxH)
     */
    size?: string | null;
    /**
     * Length
     *
     * Images size in bytes
     */
    length?: number | null;
};

/**
 * ImageSizesChoices
 */
export type ImageSizesChoices = 'ORIGINAL' | 'XL' | 'L' | 'M' | 'S';

/**
 * ProductFileDTO
 */
export type ProductFileDto = {
    /**
     * Id
     */
    id: number;
    /**
     * File
     */
    file: string;
    /**
     * Description
     */
    description?: string | null;
    meta?: ImageMeta;
};

/**
 * ProductTypeDTO
 */
export type ProductTypeDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
};

export type GetPublicData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/reviews/public/';
};

export type GetPublicResponses = {
    200: Array<ReviewDto>;
};

export type GetPublicResponse = GetPublicResponses[keyof GetPublicResponses];

export type GetProductsInStockData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/products/in_stock/';
};

export type GetProductsInStockResponses = {
    200: Array<ProductDto>;
};

export type GetProductsInStockResponse = GetProductsInStockResponses[keyof GetProductsInStockResponses];

export type RetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/';
};

export type RetrieveResponses = {
    200: unknown;
};
