# Generated by Django 5.2.7 on 2026-03-22 20:47

import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "appointment_at",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        db_comment="Интервал начала и окончания консультации (PostgreSQL tstzrange)",
                        db_index=True,
                        help_text="Укажите время начала и окончания консультации.",
                        verbose_name="Интервал приёма",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        db_comment="Описание хода приёма и итоги (HTML из редактора)",
                        verbose_name="Описание и результаты",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Стоимость консультации",
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Стоимость консультации",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_comment="Клиент (пользователь)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_comment="Сотрудник, создавший запись в админке",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор записи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приём",
                "verbose_name_plural": "Приёмы",
                "db_table": "jw_consultation",
                "ordering": ("-appointment_at",),
            },
        ),
    ]
