# Generated by Django 5.0.1 on 2025-01-04 09:41

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import root.apps.products.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bot", "0005_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                ("guid", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "title",
                    models.CharField(
                        db_comment="Product unique name",
                        max_length=255,
                        unique=True,
                        verbose_name="Unique name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        db_comment="Product`s description",
                        max_length=1000,
                        verbose_name="Description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Price",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        db_comment="Is product in stock",
                        default=True,
                        verbose_name="In stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "jw_product",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Product type name",
                        max_length=255,
                        unique=True,
                        verbose_name="Unique name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="Product type description",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="Is product type active",
                        default=True,
                        verbose_name="Is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product type",
                "verbose_name_plural": "Product types",
                "db_table": "jw_product_type",
            },
        ),
        migrations.CreateModel(
            name="ProductFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=root.apps.products.utils.upload_product_file_to,
                        verbose_name="File's link",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="File`s description",
                        max_length=1000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_comment="Product",
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product file",
                "verbose_name_plural": "Product files",
                "db_table": "jw_product_files",
            },
        ),
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_comment="Price",
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Price",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_comment="Product",
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product price history",
                "verbose_name_plural": "Product price history",
                "db_table": "jw_product_price_history",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                db_comment="Product type",
                on_delete=django.db.models.deletion.PROTECT,
                to="products.producttype",
                verbose_name="Product type",
            ),
        ),
        migrations.CreateModel(
            name="ProductChannelPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(db_comment="Message ID", verbose_name="Message ID"),
                ),
                (
                    "text",
                    models.CharField(db_comment="Publication`s text", verbose_name="Publication text"),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        db_comment="Is main publication sign",
                        default=True,
                        verbose_name="Is main publication",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        db_comment="Publication channel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_publications",
                        to="bot.channel",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_comment="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product channel publication",
                "verbose_name_plural": "Product channel publications",
                "db_table": "jw_product_channel_publication",
                "unique_together": {("product", "channel", "message_id")},
            },
        ),
    ]
