# Generated by Django 5.0.1 on 2025-01-26 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("PRODUCT", "Product"), ("SERVICE", "Service")],
                db_comment="Product category",
                default="PRODUCT",
                max_length=50,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_comment="Product type",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.producttype",
                verbose_name="Product type",
            ),
        ),
    ]
