# Generated by Django 5.0.1 on 2024-12-30 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0005_channel"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductChannelPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Creation date and time",
                        verbose_name="Creation date and time",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="Update date and time",
                        verbose_name="Update date and time",
                    ),
                ),
                (
                    "message_id",
                    models.BigIntegerField(db_comment="Message ID", verbose_name="Message ID"),
                ),
                (
                    "text",
                    models.CharField(db_comment="Publication`s text", verbose_name="Publication text"),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        db_comment="Is main publication sign",
                        default=True,
                        verbose_name="Is main publication",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        db_comment="Publication channel",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_publications",
                        to="bot.channel",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_comment="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product channel publication",
                "verbose_name_plural": "Product channel publications",
                "db_table": "jw_product_channel_publication",
            },
        ),
    ]
