# Generated by Django 5.0.1 on 2025-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_productchannelpublication"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productchannelpublication",
            unique_together={("product", "channel", "message_id")},
        ),
    ]
