# Generated by Django 5.1.5 on 2025-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_category_alter_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfiles",
            name="meta",
            field=models.JSONField(db_comment="File`s meta", default=dict, verbose_name="File's meta"),
        ),
        migrations.AddField(
            model_name="productfiles",
            name="type",
            field=models.CharField(
                choices=[("IMAGE", "Image")],
                db_comment="File`s type",
                default="IMAGE",
                max_length=50,
                verbose_name="File's type",
            ),
            preserve_default=False,
        ),
    ]
