# Generated by Django 5.1.5 on 2025-09-29 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productfiles_meta_productfiles_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfiles",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_comment="Parent file",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productfiles",
                verbose_name="Parent file",
            ),
        ),
    ]
